#!/usr/bin/env python
import os
import sys
from fl0w3r import run, error, normpath, args


def fixp(a):
    return abspath(realpath(normpath(a)))


def stripfn(a):
    b = (a.strip()).split('/')
    b = b[:-1]
    ret = "/"
    ret = ret.join(b)
    ret = ret + "/"
    return ret

if len(args) < 4:
    print 'joincol: join two 1-col ascii files generated by b2a, to create a'
    print ' 2-col file. Usage: joincol [infile1] [infile2] [outfile]\n'
    print 'By Ash Richardson 20090407 reimpl. 20170626\n'
    sys.exit(1)

i1, i2 = args[1], args[2]

print "Joining the following 1 column files:"
print fixp(i1)
print fixp(i2)

one = open(i1).readlines()
two = open(i2).readlines()

if len(one) != len(two):
    print "Error: files did not match in length"
    sys.exit(1)

n = len(one)
f = open(args[3], 'w')

for i in range(0, n):
    _1 = (one[i].strip()).split()
    _2 = (two[i].strip()).split()
    f.write(str(_1[0]) + " " + str(_1[1]) + " " + str(_2[1]) + " \n")
f.close()
